export const OPENAI_ENV = {
  API_KEY: 'OPENAI_API_KEY',
  ORG_ID: 'OPENAI_ORG_ID',
  PROJECT_ID: 'OPENAI_PROJECT_ID',
  BASE_URL: 'OPENAI_API_BASE_URL',
  TIMEOUT: 'OPENAI_API_TIMEOUT',
  MAX_RETRIES: 'OPENAI_API_MAX_RETRIES',
  BASE_PROMPT: 'OPENAI_BASE_PROMPT',
  DANGEROUSLY_ALLOW_BROWSER: 'OPENAI_API_DANGEROUSLY_ALLOW_BROWSER',
} as const;

export type OpenAiEnvKey = (typeof OPENAI_ENV)[keyof typeof OPENAI_ENV];

export const OPENAI_HEADER = {
  VAN_SCRAPPER_PROMPT: 'vanScrapper-Prompt',
} as const;
